version: "3"
services:
  node-app:
    build: 
      context: .
      args: 
        NODE_ENV: production
    environment: 
      - NODE_ENV=production
      - MONGO_USER=mongoadmin
      - MONGO_PASSWORD=Password1
    command: node index.js
  mongo:
    environment: 
      - MONGO_INITDB_ROOT_USERNAME=mongoadmin
      - MONGO_INITDB_ROOT_PASSWORD=Password1