version: "3"
services:
  node-app:
    build: 
      context: .
      args: 
        NODE_ENV: development
    volumes: 
      - ./:/app:ro
      - /app/node_modules
    environment: 
      - PORT=3000
    command: npm run dev