version: "3"
services:
  node-app:
    build: 
      context: .
      args: 
        NODE_ENV: development
    volumes: 
      - ./:/app:ro
      - /app/node_modules
    environment: 
      - PORT=3000
      - MONGO_USER=mongoadmin
      - MONG_PASSWORD=Password1
      - SESSION_SECRET=secret
    command: npm run dev
  mongo: 
    environment: 
      - MONGO_INITDB_ROOT_USERNAME=mongoadmin
      - MONGO_INITDB_ROOT_PASSWORD=Password1
